allData <- read.table("household_power_consumption.txt", header=T, stringsAsFactors = F, sep = ";")
fData <- subset(allData, allData$Date=="1/2/2007" | allData$Date == "2/2/2007")
fData$Global_active_power <- as.numeric(fData$Global_active_power)
fData$DateTime <- paste(fData$Date, fData$Time, " ")
fData$DateTime <- strptime(fData$DateTime, "%d/%m/%Y %H:%M:%S")
png("plot3.png")
plot(fData$DateTime, fData$Sub_metering_1, type="l", xlab = "", ylab = "Energy sub metering")
points(fData$DateTime, fData$Sub_metering_2, type="l", col="red")
points(fData$DateTime, fData$Sub_metering_3, type="l", col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty = 1)
dev.off()